### ISSUE TITLE
First contact

### ISSUE THREAD

**Issue by ilammy** [cpp-2016-autumn/android-process-monitoring#1]
Нужно:
- [x] ознакомиться [со спецификацией](https://github.com/cpp-2016-autumn/android-process-monitoring/files/519961/Android.Process.Monitoring.docx)
- [x] уточнить неясные детали спецификации
- [x] ознакомиться с «приложением-конкурентом» [ESET Parental Control](https://play.google.com/store/apps/details?id=com.eset.parental)
- [x] попробовать написать Hello World под Андроид
- [x] составить представление о целях проекта и общее представление об их возможной реализации

(Вопросы мы уже обсудили устно. Было бы неплохо их озвучить здесь повторно.)

**Comment by pacmancoder** [comment]
### Ознакомление со спецификацией

В ходе детального рассмотрения спецификации выделено две основных проблемы, с которыми нужно разобраться для успешного выполнения проекта. Таковыми являются:  
- Взаимодействие с платформой Firebase (Google Cloud Messaging, указанный в спецификации стал частью данной платформы под именем Firebase Cloud Messaging);  
- Способы блокировки приложений на Android.  

#### Особенности

Исследуя возможности платформы Firebase, мы нашли несколько её особенностей, исходя из которых в устной форме было обсуждено несколько уточняющих вопросов по спецификации:
- Все серверные функции такие как управление БД, аутентификация пользователей и передача сообщений перекладываются на облачный фреймворк, таким образом серверная часть проекта фактически становится еще одним клиентом, но с административными функциями. 
- Фреймворк Firebase также накладывает ограничения при выборе языка программирования. Его клиентский API в данный момент доступен на Java, Java Script и С++. 

Данные особенности приводят к вопросу:  
_На каком языке стоит писать серверную(административную) часть приложения? В спецификации предложен python, но среди официально поддерживаемых API Firebase он отсутствует._

**Comment by DancingAxolotl** [comment]
### «Приложение-конкурент» ESET Parental Control

Приложение ESET “Parental control” предложенное как «программа-конкурент» помогает осуществить родительский контроль над устройством ребенка. В свете предложенных спецификаций оно имеет несколько интересующих нас функций:
-  Приложение имеет два режима, выбор между которыми осуществляется при первом запуске. Настройки и мониторинг устройств, привязанных к одному аккаунту, осуществляется из «режима родителя», а блокировка приложений – из «режима ребенка». 
- При выборе «режима ребенка» приложение помогает включить свой сервис accessibility, также в разрешениях оно имеет возможность появляться поверх открытых программ. 
  Это дает подсказку о том, каким образом осуществляется блокировка: при запуске нежелательной программы появляется сообщение, перекрывающее её, а при попытке зайти в диспетчер задач или удалить любое из приложений появляется подобное сообщение и срабатывает кнопка «домой»
  Но это лишь теория, которая будет проверена в одном из прототипов нашего приложения. Возможно найдутся и более элегантные методы блокировки, хотя стоит заметить, что используемый способ блокировки нам обойти не удалось.

Исходя из особенностей рассмотренного приложения был поставлен вопрос:

_Можно ли реализовать административную часть приложения как отдельное Android-приложение?_

**Comment by pacmancoder** [comment]
После изучения примеров приложений Firebase попробовал создать тестовое приложение для ознакомления с инструментарием. Итого, что полезного:
- Настроил рабочее окружение для разработки, подготовил несколько тестовых устройств
- Опробовал самые главные вещи в системе сборки, предоставляемой Android Studio (Gradle) вроде подключения зависимостей, настройки структуры проекта, его параметров.
- Немного попрактиковался в работе с компонентами GUI Android
- Протестировал авторизацию и регистрацию новых пользователей в Firebase

**Comment by DancingAxolotl** [comment]
В время своих исследований пробовал создать простое приложение. А именно:
-  Установил и настроил среду разработки Android Studio
-  Настроил эмуляторы и физичиские устройства для отладки
-  Создал тестовое приложение с использованием различных элементов GUI Android
-  Реализовал связь с тестовым проектом Firebase и проверил синхронизацию данных с БД

**Comment by ilammy** [comment]
Отлично. Молодцы. :+1:

Учитывая, что Java является одним из языков API к Firebase, я считаю вполне обоснованной идею реализации приложения для административного доступа в виде отдельного Android-приложения на Java.

Спецификация не накладывает каких-либо ограничений на административную консольку («лишь бы работало»), так что это приемлемо.

Я считаю задачу выполненной в полном объёме и закрываю её. Можно переходить к следующей (#2).
