### ISSUE TITLE
Implement app list storage and caching

### ISSUE THREAD

**Issue by ilammy** [cpp-2016-autumn/android-process-monitoring#10]
Разработка логики синхронизации и кеширования списков с облаком Firebase.

Для административного приложения:
- [x] Получение списка приложений установленных на устройстве.
- [x] Отправка черного списка.

Для клиентского приложения:
- [x] Отправка списка приложений установленных на устройстве.
- [x] Получение черного списка.

Локальное кеширование данных необходимо, чтобы блокировка приложений работала и без связи с сервером или в условиях плохого канала.

**Comment by pacmancoder** [comment]
В ходе изучения Firebase API выяснилось, что там предусмотрена функция кэширования указанной части БД. Задача кэширования сводиться в к минимуму, а именно к использованию буквально одной функции Firebase API. :smile:

**Comment by pacmancoder** [comment]
Получение списка приложений и отправка чёрного списка реализованы начиная с коммита d3f822145adfd1adc7dcd4b53c270bf0202cb223, ветка develop/pacmancoder

**Comment by DancingAxolotl** [comment]
Списки приложений у клиента синхронизируются с коммита 4cf4813, develop/MikeSotnichek
