### ISSUE TITLE
Implement password management

### ISSUE THREAD

**Issue by ilammy** [cpp-2016-autumn/android-process-monitoring#11]
Реализовать вспомогательные административные действия:
- [x] Смена пароля
- [x] Восстановление пароля

**Comment by pacmancoder** [comment]
### Отчёт о проделанной работе 05.11

Был добавлен элемент управления в LoginActivity, позволяющий выполнить сброс пароля, отослав на почтовый ящик пользователя сообщение для сброса пароля.  На стороне *Firebase это выполняется вызовом `FirebaseAuth.sendPasswordResetEmail(String email);`

Смена пароля будет происходить на экране настроек приложения. Соответствующие элементы управления уже размещены и связаны с обрабатывающим их кодом.

**Comment by pacmancoder** [comment]
Реализовано начиная с коммита 8dbf6b59e0266b31b55d966566e164e1f4cbdaf, ветка develop/pacmancoder. Есть возмодность восстанавливать пароль, менять пароль, а так же менять пин-код клиентских приложений и административного приложения.
