### ISSUE TITLE
Implement login and initial data sync

### ISSUE THREAD

**Issue by ilammy** [cpp-2016-autumn/android-process-monitoring#12]
Реализация авторизации при старте приложения и начальной синхронизации с сервером.
- [x] Выполнить логин в облако.
- [x] Получить список приложений.
- [x] Отправить список и прочую информацию об устройстве на сервер.

Прототип работы с Firebase — в ветке [**prototype/firebase**](https://github.com/cpp-2016-autumn/android-process-monitoring/tree/prototype/firebase).

Прототип получения списка приложений — в ветке [**prototype/applist**](https://github.com/cpp-2016-autumn/android-process-monitoring/tree/prototype/applist).

**Comment by DancingAxolotl** [comment]
### Отчет о проделаной работе
- Сделан интерфейс логина и сервис инициализации.
- Реализована основа publisher/subscriber, на которой построена архиетктура приложения

#### Подробнее

**LoginController** управляет интерфейсом логина **LoginActivity** и отвечает за логин в облако, будет использовать разработанные совместно с @pacmancoder обертки для firebase.

**SetupService** выполняет начальную инициализацию остальных сервисов, прячет **LoginActivity** из списка приложений в менеджере пакетов и собирает список всех установленных приложений на устройстве, чтобы отправить его на сервер.

Передача сообщений между publisher/subscriber выполняется через класс-одиночку **Bus**, с помощью которого можно подписать **ISubscriber** на сообщения по определенной теме или опубликовать сообщение.

Последний коммит: dbe91370ac213893cae40950d325437884925d59 (develop/MikeSotnichek)

**Comment by DancingAxolotl** [comment]
Список приложений синхронизируется при инициализации accessibility сервиса, отвечающего за блокировку. После синхронизации список приложений на устройстве соответствует списку на сервере. Новые приложения отправляются на сервер как не заблокированные, а удаленные приложения удаляются из бд.
Коммит: 4cf4813
