### ISSUE TITLE
Implement app blocking

### ISSUE THREAD

**Issue by ilammy** [cpp-2016-autumn/android-process-monitoring#13]
Реализация механизма блокировки.
- [x] Блокировка произвольного списка приложений.
- [x] Предотвратить несанкционированную остановку сервиса блокировки.
- [x] Предотвратить несанкционированное удаление сервиса блокировки.

Прототип блокировки — в ветке [**prototype/blocking**](https://github.com/cpp-2016-autumn/android-process-monitoring/tree/prototype/blocking).

**Comment by DancingAxolotl** [comment]
Блокировка списка приложений добавлена с коммита 73b5991. Для разблокировки необходимо ввести пин-код, привязаный к аккаунту. После разблокировки приложение доступно до тех пор, пока пользователь не перейдет на любое окно, принадлежащее другому приложению.

Несанкционированная остановка и удаление сервиса предотвращаются блокировкой настроек и установщика приложений средставами самого блокировщика. Тоесть чтобы удалить приложение или остановить его процесс нужно ввести пин, как для доступа к любому другому заблокированному приложению. Блокировка настроек и установщика включена по умолчанию с коммита aba25f9
