### ISSUE TITLE
Implement auxiliary features

### ISSUE THREAD

**Issue by ilammy** [cpp-2016-autumn/android-process-monitoring#14]
Реализация дополнительных функций.
- [x] Отключение сервиса блокировки.

(_Возможно расширение списка._)

**Comment by DancingAxolotl** [comment]
Сервис блокировки можно отключить с коммита 73b5991. Чтобы включить сервис, нужно снова ввести логин и пароль.
А с коммита aba25f9 отключить сервис можно только введя перед этим пин-код.
