### ISSUE TITLE
Prepare project plan

### ISSUE THREAD

**Issue by ilammy** [cpp-2016-autumn/android-process-monitoring#2]
Нужно спланировать будущую работу по проекту.
- [x] **Примерный план**
  
  Здесь следует пересчислить примерное разбиение времени по крупным задачам (с точностью около недели). Дата завершения проекта фиксирована, напишите её тут и учитывайте.
  
  Не забудьте включить в план следующие пункты:
  - исследование реализуемости, написание прототипов
  - составление более подробного плана
  - собственно задачи разработки
  - тестирование и исправление недочётов
  - написание документации и прочая бумажная работа
  - подготовка презентации проекта
  
  Закиньте его сюда в любой удобной вам форме. Лучше сразу в комментариях. Можете также заполнить [карточки заданий в Projects](https://github.com/cpp-2016-autumn/android-process-monitoring/projects).
  
  **Срок:** 2016-10-14 (пятница)
- [x] **Уточнённый план**
  
  Здесь следует разбить выполнение проекта на подзадачи, оценить время на их выполнение, и распределить задачи между собой.
  
  Здесь важно именно _оценивание_ времени, а не его распределение. То есть вести разработку плана следует от того, сколько вы думаете, вам потребуется на подзадачу. _Не надо_ пытаться распределить наличное время (вон те четыре недели) на подзадачи. В итоге по плану должно быть возможно сказать, хватит ли вам выделенного времени, или нужно убрать некоторые задачи, или изменить общее распределение времени, или отложить срок сдачи проекта.
  
  Если не ясно, сколько потребуется времени, то разбивайте задачи на подзадачи до тех пор, пока стоимость их выполнения не будет понятной, а потом складывайте. Чем подробнее будет разбиение, тем вам же удобнее. Естественно, не надо выделять отдельные задачи на каждый класс и метод. Но желательно описать в задаче, что именно вы там хотите реализовать, а не просто абстрактная «блокировка». Также помните, что всяческие юнит-тесты (если собираетесь их писать) являются частью разработки, а не отдельной задачей.
  
  План поместите сюда в удобной вам форме. Когда он будет готов, issue насоздавать для подзадач могу я, если хотите, а вы можете уже просто приступать к разработке.
  
  **Срок:** 2016-10-24 (понедельник)

**Comment by pacmancoder** [comment]
Конечный срок сдачи проекта -  30.11

План работы:
- 03.10 - 09.10 (1 неделя)
  - Ознакомление с требованиями к проекту, исследование "приложений-конкурентов"
  - Исследование существующих инструментариев для разработки приложения данного класса
- 10.10 - 11.10 (2 дня) 
  - Уточнение неясных деталей спецификации
- 12.10 - 16.10 (5 дней)
  - Ознакомление с инструментарием разработки проекта
  - Составление предварительного плана
- 17.10 - 23.10 (1 неделя)
  - Написание прототипов
  - Составление детального плана разработки
- 24.10 - 27.10 (4 дня)
  - Определение протокола обмена данными клиентом и административного приложения через облако
  - Распределение задач в команде
- 28.10 - 17.11 (3 недели)
  - Непосредственно разработка
  - Написание тестов
- 18.11 - 23.11 (6 дней)
  - Тестирование
  - Исправление недочётов и ошибок
- 24.11 - 29.11 (6 дней)
  - Написание сопровождающей документации
  - Подготовка презентации проекта

**Comment by ilammy** [comment]
В целом, отлично! План хорош: ничего не забыли, время распределили нормально.

Есть только одно замечание. Распределение задач в команде входит в планирование. В детальном плане (aka _roadmap_) вам надо будет подробнее (чем подробнее, тем лучше и удобнее) расписать кто и какими задачами занимается, и когда они должны быть готовы. В частности, проектирование протоколов — это тоже просто одна из подзадач проекта, наряду с последующей разработкой и тестированием.

---

Я создал milestones для основных этапов, выставив им сроки завершения исходя из этого плана:
- [2016-10-23 — **Planning**](https://github.com/cpp-2016-autumn/android-process-monitoring/milestone/1)
  
  Мы сейчас здесь. По завершении будет готов полный план работ: всем будет _ясно, что делать,_ и можно будет приступать к разработке.
- [2016-11-17 — **Development**](https://github.com/cpp-2016-autumn/android-process-monitoring/milestone/2)
  
  Этап завершается заморозкой активной разработки. То есть к этому моменту уже нельзя будет добавлять новую функциональность, «всё переписать с ноля», и прочее. У вас будет _готова альфа-версия_.
- [2016-11-23 — **Stabilization**](https://github.com/cpp-2016-autumn/android-process-monitoring/milestone/3)
  
  Здесь идентифицируются, классифицируются, и по возможности исправляются недочёты, оставленные при разработке. В конце этапа проект по сути будет почти _готов к сдаче,_ release candidate.
- [2016-11-29 — **Release**](https://github.com/cpp-2016-autumn/android-process-monitoring/milestone/4)
  
  И наконец этап причёсывания проекта и приведения документации в порядок, который завершается сдачей и _защитой проекта_.

---

И такой ещё бонусный вопрос в эфир: зачем вам прототипы? В плане, что именно они вам дают, раз вы включили их в план?

**Comment by ilammy** [comment]
Для протокола, цитирую ответ @MikeSotnichek на вопрос про прототипы:

> Сейчас наибольшей проблемой для нас остается блокировка приложения. Но это фактически ключевая задача нашего проекта. Не найдя рабочего ответа мы не сможем выполнить проект. 
> 
> На данный момент есть лишь нечеткая теория. Её подверждение на практике это залог успеха. И будет очень печально если она опровергнется в ходе разработки.
> 
> Создав прототип мы подтвердим или опровергнем её еще до начала разработки и успеем принять соответствующие меры. Либо окончательно уберем эту неизвестную)
> 
> А дальше отталкиваясь от этого решения пойдет разработка. Как вы написали "всем будет ясно что делать"
> 
> Мне кажется что наш нынешний план операется именно на разработку прототипа.
> 
> (_via Skype, 2016-10-14_)

**Comment by pacmancoder** [comment]
Итак,  был обсуждён и сформирован **уточнённый план**.

## Этап разработки (24.10 - 18.11, 3 недели)

### Согласование и утверждение архитектуры (24.10 - 28.10, 4 дня)

**Участники:** @pacmancoder, @MikeSotnichek  

Выполняется путём обсуждения в устной форме и закрепление сделанных выводов в
соответствующей issue на Github.

#### Подзадачи:
- Описание структуры БД и правила обмена данными;
- Описание структур приложения-клиента и административного приложения;
- Предложения по организации и взаимосвязи модулей в проекте Android Studio.

### Основной этап разработки (29.10 - 11.11, 2 недели)

### Административное приложение

**Ответственный:** @pacmancoder  
Необходимо реализовать основной функциональности приложения - загрузка
информации о приложениях подконтрольных устройств, формирование чёрных списков,
а так же возможность управления аккаунтом - изменение мастер-пароля,
восстановление пароля от аккаунта и синхронизация всех данных с БД.
Выполнение тестирования в ручном режиме, а также написание автоматических
тестов.  

#### Подзадачи:
- Проектирование GUI _(29.10 - 01.11, 4 дня)_
  - Основные Activity для логина/регистрации пользователя
  - Activity для смены пароля аккаунта, клиентского мастер-пароля.
  - Activity для выбора подконтрольного устройства
  - Activity для управления чёрным списком приложений, поиск по приложениям
  - Установление взаимосвязей между activity, логика переходов между ними
- Интеграция Firebase Auth, Firebase Realtime DB _(02.11 - 03.11, 2 дня)_
  - На основе прототипа
    [работы с  firebase](/cpp-2016-autumn/android-process-monitoring/tree/prototype/firebase)
    реализовать логику входа и регистрации пользователей
  - На основе того же прототипа реализовать загрузку/выгрузку данных о списках
    пользователя
- Синхронизация и кеширование списка приложений
  _(04.11 - 07.11, 4 дня)_
  - Разработка логики синхронизации и кеширования списков с облаком firebase
    совместно с @MikeSotinchek (см. соответствующую задачу ниже)
  - Получение списка приложений установленных на устройстве на сервер
  - Отправка черного списка
- Реализация вспомогательных административных действий - смена пароля и его
  восстановление. _(08.11 - 11.11, 4 дня)_
  - Смена пароля
  - Восстановление пароля

#### Риски:

Есть риск нехватки времени из-за довольно большого объема работы, но
он может быть компенсирован на последней неделе стадии разработки проекта,
взаимной помощью участников. Перед стартом этапа разработки были созданы
прототипы, которые должны ускорить внедрение Firebase и разработку UI, это
является вторым компенсирующим фактором. Исходя из этого можно сказать что
сроки выполнения проекта могут быть удовлетворительны без задержек.

### Клиентское приложение

**Ответственный:** @MikeSotinchek
Реализовать необходимый функционал, а именно авторизацию пользователей,
синхронизацию черного списка и списка приложений на данном устройстве,
блокировку доступа к приложениям из черного списка. Ручное и автоматическое
тестирование компонентов.

#### Подзадачи:
- Авторизация, начальная синхронизация с сервером (29.10 - 1.11, 4 дня)
  - Взять прототипы [лоигна](/cpp-2016-autumn/android-process-monitoring/tree/prototype/firebase) и [получения списка приложений](/cpp-2016-autumn/android-process-monitoring/tree/prototype/applist)
  - Добавить отправку данных на сервер, нужных для привязки нового устройства к аккаунту
- Синхронизация списков, управление кешированными данными (2.11 - 6.11, 5 дней)
  - Синхронизация и кеширование данных, необходимых для блокировки при
    отсутствии связи с сервером или в условиях медленного интернета
    (совместно с @pacmancoder)
  - Отправка списка приложений установленных на устройстве на сервер
  - Получение черного списка
- Реализация механизма блокировки (7.11 - 9.11, 3 дня)
  - Взять прототип [блокировки](/cpp-2016-autumn/android-process-monitoring/tree/prototype/blocking)
  - Расширить его для блокировки произвольного списка приложений
  - Предотвратить несанкционированне удаление и остановку сервиса блокировки
- Реализация доп. функций (смена пользователя, выключение сервиса и т.п.) (10.11 - 11.11, 2 дня)
  - Реализовать отключение сервиса

#### Риски:

Малые. Создание прототипов показало что задание выполнимо и непредвиденные
ситуации не ожидаются. И как дополнительная предосторожность будет 3-я неделя
разработки, которая отводится под совместную работу и взаимопомощь.
Так что, хоть работа и объемная, мы приняли меры предосторожности чтобы
свести риски к минимуму и успеть выполнить все в срок.

### Интеграция (12.11 - 18.11, 1 неделя)

**Участники:** @pacmancoder, @MikeSotnichek  

На этом этапе нужно довести до конца все незаконченные подзадачи, которые
по тем или иным причинам не были окончены в срок. Как только отдельные
части будут готовы необходимо разрешить проблемы, возникшие при их совмещении.
Окончательно согласовать работу административного и клиентского приложений.

### Тестирование (19.11 - 23.11, 5 дней)

**Участники:** @pacmancoder, @MikeSotnichek  
Подзадачи выполняются параллельно всеми членами команды.
Сразу за обнаружением ошибки следует её устранение.
Система должна тестироваться в рабочей обстановке и при разных условиях.
Необходимо проверить как взаимодействие административного и клиентского
приложений между собой так и финкционал каждого по отдельности.

#### Подзадачи:
- Составление тест-плана (19.11, 1 день)
- Поиск и исправление ошибок и недочётов (20.11 - 23.11, 4 дня)

### Подготовка к релизу (24.11 - 29.11, 6 дней)

**Участники:** @pacmancoder, @MikeSotnichek  

Последний этап разработки. Подготовка продукта к презентации.

#### Подзадачи:
- Написание сопровождающей документации [@MikeSotnichek]
- Подготовка релизных сборок [@pacmancoder]
- Подготовка презентации проекта [@pacmancoder, @MikeSotnichek]

**Comment by ilammy** [comment]
@pacmancoder, @MikeSotnichek, молодцы :+1: Хороший план.

Я навёл красоту в issues:
- [Design architecture and protocols](4)
- [Implement control app](5)
- [Implement blocker app](6)
- [Integrate control and blocker apps](7)

Ну и, собсно, планирование считаю завершённым. В добрый путь! *разбивает бутылку*
