### ISSUE TITLE
Prepare testing plan

### ISSUE THREAD

**Issue by ilammy** [cpp-2016-autumn/android-process-monitoring#20]
Нужно составить план тестирования.

В нём следует в целом описать, что за компоненты у вас есть и что в них следует проверить, а также сделать список _тест-кейсов_. В тест-кейсах следует не забыть указать:

- что проверяется
- шаги проверки
- что ожидается в результате

Прохождение набора тест-кейсов должно показывать, что ваше приложение работает в основных вариантах использования, которые описаны [в спецификации](1). Тест-кейсы можно разделить по приоритетам:

- критические: если не работает, приложение бесполезно
- обычные
- низкоприоритетные: редкие варианты использования, их поломка не критична

**Comment by DancingAxolotl** [comment]
Готовый план тестирования:
 - для административного приложения: [test_cases_control.pdf](https://github.com/cpp-2016-autumn/android-process-monitoring/files/619886/test_cases_control.pdf) (написан @pacmancoder)
 - для клиентского приложения: [test_cases_client.pdf](https://github.com/cpp-2016-autumn/android-process-monitoring/files/619993/test_cases_client.pdf) (написан мной)

**Comment by ilammy** [comment]
:+1:
