### ISSUE TITLE
Create user documentation

### ISSUE THREAD

**Issue by ilammy** [cpp-2016-autumn/android-process-monitoring#22]
Подготовить _пользовательскую_ документацию на продукт:

- что здесь вообще есть за возможности
- как установить блокировалку
- как настроить блокирование
- как администрировать список устройств
- и так далее

Лучше всего её закинуть на вики или на Github Pages.

**Comment by DancingAxolotl** [comment]
Документация готова. Информация для пользователей на [вики](https://github.com/cpp-2016-autumn/android-process-monitoring/wiki). Диаграммы классов, sequence и activity диаграммы в [репозитории](https://github.com/cpp-2016-autumn/android-process-monitoring/tree/master/docs/diagrams).

**Comment by ilammy** [comment]
Зашибись :+1: :tada:
