### ISSUE TITLE
Prepare for project presentation

### ISSUE THREAD

**Issue by ilammy** [cpp-2016-autumn/android-process-monitoring#24]
Подготовить презентацию проекта.

На презентации следует упомянуть:

- что это вообще за проект
- что было в спецификации, что реализовали, что изменили
- как вы распределили и организовали работу
- общая архитектура проекта, какие паттерны использовали, и т. п.
- интересные понравившиеся штуки при реализации
- как тестировался проект, какие проблемы вы нашли при тестировании
- общее впечатление, замечания, предложения, угрозы

Естественно, должно быть и live demo работы приложения.

Ссылку на слайдики можно бросить сюда в комментарии.

**Comment by DancingAxolotl** [comment]
Презентация готова к демонстрации: [Appmon.pptx](https://github.com/cpp-2016-autumn/android-process-monitoring/files/632089/Appmon.pptx)

**Comment by ilammy** [comment]
Презентацию не смотрел. Не люблю спойлеры :)
