### ISSUE TITLE
Perform acceptance testing

### ISSUE THREAD

**Issue by ilammy** [cpp-2016-autumn/android-process-monitoring#25]
- [x] Провести приёмочное тестирование по плану из #20.
- [x] Сделать выводы о годности продукта.

## Легенда

- :grey_question: — кейс не проверялся
- :white_check_mark: — кейс пройден успешно
- :x: — кейс провален

## Административное приложение

<table>
  <tr>
    <th>Priority</th><th>Title</th><th>Result</th>
  </tr>

  <tr>
    <th colspan=3><i>Регистрация в системе</i></th>
  </tr>
  <tr>
    <td><b>Critical</b></td>
    <td>Регистрация в нормальных условиях</td>
    <td>:white_check_mark:</td>
  </tr>
  <tr>
    <td>Normal</td>
    <td>Регистрация с невалидным email</td>
    <td>:white_check_mark:</td>
  </tr>
  <tr>
    <td>Normal</td>
    <td>Регистрация со слишком коротким паролем</td>
    <td>:white_check_mark:</td>
  </tr>
  <tr>
    <td>Normal</td>
    <td>Регистрации в условиях отсутствия интернета</td>
    <td>:white_check_mark:</td>
  </tr>

  <tr>
    <th colspan=3><i>Вход в систему</i></th>
  </tr>
  <tr>
    <td><b>Critical</b></td>
    <td>Вход в нормальных условиях</td>
    <td>:white_check_mark:</td>
  </tr>
  <tr>
    <td>Normal</td>
    <td>Вход в несуществующий аккаунт</td>
    <td>:white_check_mark:</td>
  </tr>
  <tr>
    <td>Normal</td>
    <td>Вход с неправильным паролем</td>
    <td>:white_check_mark:</td>
  </tr>
  <tr>
    <td>Normal</td>
    <td>Восстановление пароля</td>
    <td>:white_check_mark:</td>
  </tr>

  <tr>
    <th colspan=3><i>Изменение настроек</i></th>
  </tr>
  <tr>
    <td>Normal</td>
    <td>Изменение пароля в нормальных условиях</td>
    <td>:white_check_mark:</td>
  </tr>
  <tr>
    <td>Normal</td>
    <td>Изменение пароля на слишком короткий</td>
    <td>:white_check_mark:</td>
  </tr>
  <tr>
    <td>Normal</td>
    <td>Ошибка при повторном вводе пароля</td>
    <td>:white_check_mark:</td>
  </tr>
  <tr>
    <td>Normal</td>
    <td>Изменение административного пин-кода в нормальных условиях</td>
    <td>:white_check_mark:</td>
  </tr>
  <tr>
    <td>Normal</td>
    <td>Изменение административного пин-кода на слишком короткий</td>
    <td>:white_check_mark:</td>
  </tr>
  <tr>
    <td>Normal</td>
    <td>Ошибка при повторном вводе административного пин-кода</td>
    <td>:white_check_mark:</td>
  </tr>
  <tr>
    <td>Normal</td>
    <td>Смена клиентского пин-кода в нормальных условиях</td>
    <td>:white_check_mark:</td>
  </tr>
    <tr>
    <td>Normal</td>
    <td>Изменение клиентского пин-кода на слишком короткий</td>
    <td>:white_check_mark:</td>
  </tr>
  <tr>
    <td><i>Low</i></td>
    <td>Ошибка при повторном вводе административного пин-кода</td>
    <td>:white_check_mark:</td>
  </tr>

  <tr>
    <th colspan=3><i>Управление чёрным списком приложений</i></th>
  </tr>
  <tr>
    <td><b>Critical</b></td>
    <td>Изменение состояния блокировки приложений</td>
    <td>:white_check_mark:</td>
  </tr>
  <tr>
    <td><i>Low</i></td>
    <td>Поиск приложений</td>
    <td>:white_check_mark:</td>
  </tr>

</table>

## Клиентское приложение

<table>

  <tr>
    <th>Priority</th><th>Title</th><th>Result</th>
  </tr>

  <tr>
    <th colspan=3><i>Логин</i></th>
  </tr>
  <tr>
    <td><b>Critical</b></td>
    <td>Логин с доступом к сети</td>
    <td>:white_check_mark:</td>
  </tr>
  <tr>
    <td><b>Critical</b></td>
    <td>Логин без доступа к сети</td>
    <td>:white_check_mark:</td>
  </tr>
  <tr>
    <td><b>Critical</b></td>
    <td>Логин с неправильным паролем</td>
    <td>:white_check_mark:</td>
  </tr>

  <tr>
    <th colspan=3><i>Блокировка приложений</i></th>
  </tr>
  <tr>
    <td><b>Critical</b></td>
    <td>Блокировка и разблокировка приложений</td>
    <td>:white_check_mark:</td>
  </tr>

  <tr>
    <th colspan=3><i>Синхронизация списка приложений</i></th>
  </tr>
  <tr>
    <td><b>Critical</b></td>
    <td>Установка приложений</td>
    <td>:white_check_mark:</td>
  </tr>
  <tr>
    <td><b>Critical</b></td>
    <td>Удаление приложений</td>
    <td>:white_check_mark:</td>
  </tr>

  <tr>
    <th colspan=3><i>Предотвращение несанкционированного выключения или удаления сервиса</i></th>
  </tr>
  <tr>
    <td><i>Low</i></td>
    <td>При "свежей" установке сервиса</td>
    <td>:white_check_mark:</td>
  </tr>
  <tr>
    <td><i>Low</i></td>
    <td>При изменениях в черном списке</td>
    <td>:white_check_mark:</td>
  </tr>

  <tr>
    <th colspan=3><i>Выключение сервиса</i></th>
  </tr>
  <tr>
    <td><i>Low</i></td>
    <td>Попытка выключения сервиса</td>
    <td>:white_check_mark:</td>
  </tr>

</table>

## How to use

1. Проверяем тест-кейсы.
2. Заносим результаты в табличку выше (у вас должны быть права на редактирование).
3. ??????
4. В ПРОДАШКН

**Comment by DancingAxolotl** [comment]
- Приемочное тестирование проведено и все найденные ошибки исправленны в пулл-реквесте #26 
 - Продукт годен для сдачи, поскольку проверенные тест-кейсы полностью покрывают [спецификацию](https://github.com/cpp-2016-autumn/android-process-monitoring/files/519961/Android.Process.Monitoring.docx).
