### ISSUE TITLE
Prototyping

### ISSUE THREAD

**Issue by ilammy** [cpp-2016-autumn/android-process-monitoring#3]
Обсудили устно, что для более точного планирования требуется написать прототипы решений:
- [x] **Блокирование activity**
  
  Попробовать повторить подход с accessibility-сервисом.
- [x] **Получение списка установленных приложений**
  
  Выяснить, как это можно сделать.
- [x] **Работа с серверной частью**
  
  Потыкать палочкой API Firebase.

Напишите здесь, пожалуйста, кто за что взялся.

Здесь же следует отобразить результаты работы (что вышло, а что нет), и дать ссылки на собственно прототипы. Код прототипов можно разместить в отдельных ветках этого репозитория:

```
$ git checkout --orphan prototype/blocking
$ ...
$ git commit src
$ git push github
```

По идее прототипы независимы и ревьювить там нечего, так что всякие pull requests не надо создавать. Просто сохраните код в репозитории.

**Срок:** 2016-10-23 (исследовательская задача).

**Comment by pacmancoder** [comment]
Задача _"Получение списка приложений"_ выполнена. Простое приложение для полученя списка установленных приложений и названий их пакетов находиться в ветке [prototype/applist](/cpp-2016-autumn/android-process-monitoring/tree/prototype/applist)

**Comment by pacmancoder** [comment]
Задача  "Работа с серверной частью" выполнена. Была опробована авторизация пользователей и привязанное к ним личное хранилище в Firebase Realtime Database. Прототип умеет автоматически синхронизировать некий список с  сервером и изменять его состояние. Таким образом при установке приложения на несколько устройств мы будем видеть в реальном времени его изменения на всех устройствах. Ссылка на ветку: [prototype/firebase](/cpp-2016-autumn/android-process-monitoring/tree/prototype/firebase)

#### Что нового выяснилось в процессе
- Административному приложению необходима защита от бесконечной регистрации пользователей - проверка e-mail и таймаут на повторную регистрацию.
- Приложение должно хранить на устройстве (кэшировать) последние считанные данные - списки приложений, черные списки  и прочее, так как _начальная_ загрузка данных при открытии приложения бывает довольно длительной (3-5 секунд). Или как вариант, если не будет хватать времени -индикация синхронизации с сервером.

**Comment by DancingAxolotl** [comment]
И наконец _"Блокирование activity"_ выполнено. Как и ожидалось, сервис Accessibility позволяет отслеживать события в запущенных приложениях и выполнять действия "вместо" пользователя.
Прототип блокирует доступ к нескольким стандартным приложениям, открывая доступ только после ввода предопределенного пароля. Приложение остается заблокированным при повторном доступе. Прототип находится в ветке: [prototype/blocking](https://github.com/cpp-2016-autumn/android-process-monitoring/tree/prototype/blocking)

**Comment by ilammy** [comment]
Отлично, :+1: 

Ящитаю, с прототипами всё.
