### ISSUE TITLE
Design architecture and protocols

### ISSUE THREAD

**Issue by ilammy** [cpp-2016-autumn/android-process-monitoring#4]
Обсудить и согласовать архитектуру продукта и протоколы взаимодействия
его частей.
- [x] Структура базы данных и правила обмена данными.
- [x] Структура приложения-клиента и административного приложения.
- [x] Организация и взаимосвязь модулей в проекте Android Studio.

Обсуждение можно вести в устной форме. В комментариях следует
отобразить результаты обсуждений и принятые решения.

**Срок:** 2016-10-28

**Comment by pacmancoder** [comment]
### Организация и взаимосвязь модулей в проекте Android studio

Всего в проекте 3 модуля:
- **client** (Клиентское приложение)
  - зависит от **shared**
- **control** (Административное приложение)
  - зависит от **shared**
- **shared** (Часть кода и ресурсов, разделяемая между приложениями)

Клиентское и административное приложения сильно отличаются по своей структуре.
Клиентское приложение имеет уклон на максимальную скрытность, большая его часть
реализуется в виде accessability сервиса. Административное приложение в свою
очередь, наоборот имеет максимальную интерактивность - activity для
реализации управления чёрным списком, паролями устройств, настройки аккаунта,
регистрация/вход. Так же у приложений есть части, которые являются общими.
Например, классы, описывающие информацию о приложении, устройстве,
классы-обёртки над подсистемами firebase.

Соответствующая структура проекта была сформирована коммитом 699d3fbe2c90c13af55b14b3ae7491f5e9a2e4eb. Таким образом репозиторий уже готов к началу этапу параллельной разработки клиентского и административного приложений

**Comment by DancingAxolotl** [comment]
### Структура базы данных и правила обмена данными.

БД firebase представленная в виде JSON, что добавляет определённые
особенности при разработке её структуры.

Как выяснилось при доступе к элементу списка API Firebase
загружает все его внутренние элементы. При линейной структуре, например:
- Идентификатор пользователя
  - Идентификатор девайса
    - Название пакета приложения

Чтобы получить список устройств в административном приложении, нужно загрузить
все списки приложений, а это пустая трата трафика и ненужное замедление работы
программы.

На клиентской части, приложение изначально знает ID устройства, и
может работать только с веткой БД, важной конкретно для данного устройства.

В ходе обсуждения была предложена такая структура БД для Firebase:
- User ID
  - Devices
    - Device ID
      - Name
    - Master password
  - Apps
    - Device ID
      - Package name
        - Application name
        - Blocking state

Такая структура позволяет быстро получать список устройств, и при этом каждое
устройство знает свой идентификатор, а значит сможет быстро получить доступ к
своему списку приложений. К примеру так, **/users/$userid/apps/$deviceid**. Тоже самое касается и получения приложений конкретного устройства из списка в
административной части.

Обмен данными между клиентской и административной частью будет осуществляться
не на прямую, а через соответствующие элементы
базы данных. Firebase позволяет отслеживать изменения определенных участков бд,
тогда приложения будут реагировать на изменения, сделанные друг-другом.

**Comment by pacmancoder** [comment]
### Архитектура административного приложения

Для общей организации архитектуры приложения было решено использовать
популярный для разработки Android-приложений паттерн
_MVP(Model-View-Presenter)_.
- **View** - Activities
- **Presenter** - Business logic
- **Model** - Data managing (Firebase API, Android DB, etc.)

#### View

_Activity_ будут заняты исключительно передачей данных о действиях пользователя
_Presenter_-у и обработкой запросов от него (на отображение информации)

#### Model

_Model_ будет представлять конкретные данные, относящиеся к той или иной части
системы. К примеру, _UserModel_ может отвечать за получение и изменение данных
о текущем пользователе с помощью _Firebase API_.
_Firebase Auth_. _AppListModel_ может отвечать за хранение и обработку забросов
на изменение данных о списке приложений.
Принимает запросы от _Presenter_ и отсылает обратно результат выполнения
операции.

#### Presenter

Является связующим звеном между _View_ и _Model_. Реализует всю бизнес-логику,
посылает запросы на изменение данных в _Model_, а также получает от него
резальтат выполнения операций. _Presenter_ посылает в _View_ запросы на
изменение графического интерфейса

### Детали

Взаимосвязь между частями паттерна _MVP_ будет происходить с помощью интерфейсов и
перекрёстных ссылок друг на друга.

Так как все три составляющие связаны только на уровне интерфейсов, то они
являются независимыми, и одна модель, к примеру может быть использована для
нескольких _Presenter_-ов и так далее. К примеру, модель _User_ может быть
использована как при регистрации так и при входе пользователя.

Корневые классы _Firebase_ есть классами-одиночками, а значит накладных расходов
при частом создании-удалении _Model_ во время смены _Activity_ не будет
наблюдаться, а хранение дополнительных данных будет организовано стандартными
средствами _Android_, например, встроенная БД _SQLite_, которая так же добавляет
каких-либо дополнительных проблем. В случае их появления будет рассматриваться
использование дополнительных классов-одиночек или других доступных методов для
того чтобы уменьшить потребление памяти или временные задержки.

Части _Model_, в свою очередь, могут являться общими классами для обеих
(административного и клиентского) приложений. Общность кода на этом уровне
позволяет быть архитектуре двух приложений независимой друг от друга, так как
их принципы работы являются различными.

**Comment by DancingAxolotl** [comment]
### Архитектура клиентского приложения

Архитектура клиентского приложения довольно экзотична, поскольку имеется много компонентов, обменивающихся данными друг с другом. Такое поведение можно реализовать с помощь паттерна publisher/subscriber. Тогда такие компоненты как:
- Обертка для работы с firebase
- Accessibility сервис для блокировки приложений
- Сервис отслеживающий изменения в списке установленных устройств
- Сервис который выводит окно "Приложение заблокированно" поверх недоступных приложений

Связывать их будет общий компонент Bus, задача которого принимать входящие сообщения и раздавать их заинтересованным получателям. Компоненты при инициализации подпишутся на интересующие их сообщения и смогут обрабатывать их по мере поступления.

Также для реализации логина пользователя будет простой activity который, при удачной попытке авторизации, попросит отдельный сервис инициализации провести начальную синхронизацию и запустить остальные сервисы приложения.

**Comment by ilammy** [comment]
В целом выглядит логично, замечаний нет :+1:

@pacmancoder,

> Корневые классы Firebase есть классами-одиночками

А это не помешает тестируемости модели, которая от них зависит?

> В случае их появления будет рассматриваться использование дополнительных классов-одиночек

**ProTip:** в любой непонятной ситуации — добавляй синглтон! :pill:

**Comment by pacmancoder** [comment]
Для протокола: цитата @ilammy 

> У одиночки же есть два аспекта:
> 1. Он поддерживает только один экземпляр объекта.
> 2. Есть возможность добраться до этого экземпляра отовсюду.
> 
> Вот вы, я так понял, хотели использовать первый, чтобы избежать 
> пересоздания подключения к Firebase. Он-то как раз тестируемости не мешает.
> 
> Тестируемости мешает второй аспект, потому что из-за него можно слишком 
> тесно привязать пользователей этого одиночки к нему. Если в кажом методе писать
> 
> Firebase.getConnection().doStuff(...);
> 
> то вы, очевидно, не сможете тестировать логику модели без подключения к Firebase и т. д
> _(via Skype, 2016-10-29)_

#### Решение проблемы

В ходе обсуждения было решено использовать Dependency Injection, и предоставлять моделям доступ к ресурсам вроде Firebase, передавая их как зависимость, используя интерфейсы. Таким образом при юнит-тестировании можно будет легко подменить зависимости на Mock-объекты.

Сами зависимости в реальном приложении действительно могут быть синглтонами (но не обязательно) - так как, например, являются, по-сути только обёрткой над Firebase.

Зависимости же при тестировании можно, создавать как обычные объекты, изменять из параметры и реализации объектов-зависимостей от теста к тесту, делая процесс прохождения отдельного теста независимым.

**Comment by ilammy** [comment]
:sparkles:
