### ISSUE TITLE
Implement control app

### ISSUE THREAD

**Issue by ilammy** [cpp-2016-autumn/android-process-monitoring#5]
Необходимо реализовать основную функциональность административного приложения:
- загрузка информации о приложениях подконтрольных устройств;
- формирование чёрных списков;
- возможности управления аккаунтом:
  - изменение мастер-пароля;
  - восстановление пароля от аккаунта;
  - синхронизация всех данных с БД.

**Срок:** 2016-11-11 ([обоснование](https://github.com/cpp-2016-autumn/android-process-monitoring/issues/2#issuecomment-255603894))
## Подзадачи
- [x] [Implement GUI for control app](8)
- [x] [Implement Firebase Auth and DB interface](9)
- [x] [Implement app list storage and caching](10)
- [x] [Implement password management](11)

**Comment by pacmancoder** [comment]
Все подпункты задачи выполнены. Pull request #18 (merged)
