### ISSUE TITLE
Integrate control and blocker apps

### ISSUE THREAD

**Issue by ilammy** [cpp-2016-autumn/android-process-monitoring#7]
Необходимо собрать конструктор воедино.
- [x] Подготовить оба приложения к интеграции.
- [x] Разрешить очевидные проблемы, появивишиеся в результате интеграции.

Пожалуйста, документируйте здесь все проблемы, возникшие и исправленные в процессе интеграции.

**Срок:** 2016-11-18

**Comment by pacmancoder** [comment]
Приложения были подготовлны к совместной работе и опробованы. 
Основные функции выполняют в полном объеме. Приложения блокируются, изменение чёрного списка в административном приложении сразу же отражается на клиентских устройствах.
Были обнаружены небольшие недочёты, в часности в графических интерфейсках - как в клиентском приложении так и в административном. Будут поправлены в ближайших коммитах.

**Comment by pacmancoder** [comment]
Была добавлена установка пин-кода по умолчанию (0000). 
Исправлена ошибка, из-за которой пин-код административного приложений не очищался. 
via commit 4bc0ef202da303352dd8a6bd97a247f7ee5d6361

**Comment by pacmancoder** [comment]
Добавлено отображение надписи "No devices found", если пока не было подсоеденено каких-либо клиентских устройств. Исправлена ошибка с "бесконечным" изменением пароля при отсутствии сети или когда авторизация была выполнена давно (недавний вход требуется Firebase). Похожая ошибка была исправлена при изменении клиентского пин-кода.
via commits 92a5875aae2a92d3b11f79c9cee743c173ea2bb2, d2220705182641f9fe6dcb736f66d2c730f82568

**Comment by pacmancoder** [comment]
Что ж, можно сказать что все *очевидные* проблемы, *замеченные* нами были решены. Отчёт о последней "пачке" очень мелких недочётов находится [здесь](https://github.com/cpp-2016-autumn/android-process-monitoring/pull/26).

Я и @MikeSotnichek считаем что issue исчерпана, можно закрывать.
