### ISSUE TITLE
Implement Firebase Auth and DB interface

### ISSUE THREAD

**Issue by ilammy** [cpp-2016-autumn/android-process-monitoring#9]
- [x] Регистрация новых пользователей.
- [x] Вход зарегистрированных пользователей.
- [x] Загрузка/выгрузка данных о списках приложений пользователя.

Прототип работы с Firebase — в ветке [**prototype/firebase**](https://github.com/cpp-2016-autumn/android-process-monitoring/tree/prototype/firebase).

**Comment by pacmancoder** [comment]
Вход и регистрация реализованы вместе с issue #11 в коммите 8dbf6b59e0266b31b55d966566e164e1f4cbdafe.
Загрузка/выглузка даных о списках приложений пользователя реализованы в d3f822145adfd1adc7dcd4b53c270bf0202cb223, ветка develop/pacmancoder.
